### ISSUE TITLE
Bug: ModuleNotFoundError: No module named 'amazon_paapi'

### ISSUE THREAD

**Issue by ahmdsabbir** [sergioteula/python-amazon-paapi#110]
**Steps to reproduce**
1. pip install python-amazon-paapi
2. wrote the line on top of paapi.py: from amazon_paapi import AmazonApi
3. run the script: py paapi.py

**Code example**
from config import AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_ASSOCIATE_TAG
from amazon_paapi import AmazonApi

print('hello')

```
**Current behavior**
always gives the ModuleNotFoundError on line 2. Even if I reinstall python-amazon-paapi using pip

**Expected behavior**
I shouldn't get this error, right?

**Comment by sergioteula** [comment]
If I'm not wrong, this is solved. Thanks!
