### ISSUE TITLE
TypeError: 'NoneType' object is not callable raised by wrapped API

### ISSUE THREAD

**Issue by YPCrumble** [sergioteula/python-amazon-paapi#13]
Thank you for building this repo, and for being so responsive! Also thanks for making the license change.

I'm getting this exception in my code after a 400 response from Amazon:

```
Exception ignored in: <function ApiClient.__del__ at 0x10e10e268>
Traceback (most recent call last):
  File "/Users/myuser/.virtualenvs/mysite/lib/python3.7/site-packages/paapi5_python_sdk/api_client.py", line 104, in __del__
  File "/usr/local/var/pyenv/versions/3.7.0/lib/python3.7/multiprocessing/pool.py", line 539, in close
TypeError: 'NoneType' object is not callable
```

I'm still investigating and will make a PR if I find any issues I can fix, but leaving this here for now in case other users encounter the same problem.

**Comment by sergioteula** [comment]
Thanks for your help, I will test it and try to solve the issue. Let me know if you find the bug by your side.

**Comment by YPCrumble** [comment]
@sergioteula it may be a bug in the underlying wrapper. Turned out that before the migration my account's tag worked both as mysite-#### and as mysite##-##. Now only mysite##-## works.

I changed the tag and now the error is gone. So, to reproduce the error just try using an incorrect site tag - you'll get a 400 error and likely also the underlying exception. Probably an issue with the wrapper, feel free to close this.

**Comment by YPCrumble** [comment]
@sergioteula confirmed it's a bug in the underlying wrapper. The issue is they're calling `self.pool.close()` in the library's __del__ method and self.pool is already None. Therefore the error.

I believe they need to do something like https://github.com/dask/dask/commit/b3d2c2c50f24a9522c10528d9ee3f529492b3cef to register this if they want to call `self.pool.close`.

I've sent an email to the SDK maintainer and will let you know if I hear back. Closing this for now.

**Comment by sergioteula** [comment]
Thanks a lot for your help, noted about the issue.

**Comment by YPCrumble** [comment]
@sergioteula re-opening this as it's currently a serious bug for me and there's no response from the developer of the API wrapper. Something I'm wondering is whether we could manually add a forked version of that wrapper to this repo to avoid the bug.

**Comment by YPCrumble** [comment]
Here's my thought. It turns out the PyPI package is simply a [download from here](https://webservices.amazon.com/paapi5/documentation/quick-start/using-sdk.html#python) uploaded to PyPI. 

My suggestion is to include that download in this repository so we can fix bugs in the Amazon version within this repo. That way we also don't depend on the PyPI version.

Alternatively, create your own PyPI upload of the Python SDK with its own GitHub repo. The problem is that the current PyPI version has no GitHub repo and so there's no way of implementing bugfixes. That could be better from a bugfixing perspective and for separation of concerns. Then reference your new upload to PyPI vs. the current amightygirl version.

I'm also happy to do that on my end if you'd prefer - just let me know. I'm eager to figure out how to fix the `self.pool.close()` bug as I'm getting it quite often at this point.

**Comment by YPCrumble** [comment]
Added a StackOverflow question: https://stackoverflow.com/q/60684183/2532070

**Comment by sergioteula** [comment]
Hello again, that's exactly how this repo worked at the begining, so I would add the official SDK just inside this package in order to be able to fix issues like this one and also avoid any dependencies. I will upload an update in a while with this change and also improving the throttling part. Keep you posted.

**Comment by sergioteula** [comment]
Already added the SDK inside this project. We can now modify it if necessary to fix any bug we find. Please check before merging into master. https://github.com/sergioteula/python-amazon-paapi/pull/19

**Comment by sergioteula** [comment]
So now we can close this issue, I hope it will be completely solved. Thanks!
