### ISSUE TITLE
Allow the user to disable throttling, or to set throttling to a value greater than one.

### ISSUE THREAD

**Issue by YPCrumble** [sergioteula/python-amazon-paapi#17]
I believe my understanding is correct that the maximum requests per second currently is one request per second? For users with a higher rate limit it would be ideal to be able to either turn off throttling or set throttling to a number greater than one.

I suggest allowing any positive number to allow more requests per second, and to allow `0` or `False` to disable throttling altogether.

Happy to make a PR at some point when I find time if this makes sense and would be helpful!

**Comment by sergioteula** [comment]
I was thinking about this when I uploaded the last update, you're right. I think the best solution is to allow using False for disabling throttling and allow higher numbers to allow more requests in a second. Maybe today or tomorrow I can work on this, anyway if you start working before me, please let me know it to avoid working both on the same feature. Thanks a lot!

**Comment by sergioteula** [comment]
I have started a pull request with the changes to throttling and adding the SDK. Please check it before merging to master. Thanks! https://github.com/sergioteula/python-amazon-paapi/pull/19

**Comment by sergioteula** [comment]
If everything is OK with pull request #19 I can merge it and start working on other issues.
