### ISSUE TITLE
TypeError 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by YPCrumble** [sergioteula/python-amazon-paapi#18]
Just received this error when a user tried searching for a string with a forward slash inadvertently in it: `Oona out of/`

Stack trace:

![image](https://user-images.githubusercontent.com/12019216/76671352-351a2280-656c-11ea-9ba7-7e67e58c4e61.png)

**Comment by YPCrumble** [comment]
One option would be to check `response.search_result.items is not None` as well.

**Comment by sergioteula** [comment]
So what the issue is here? Using a string with `/` as an argument causes this error? If so, we can check strings to remove any problematic character or, as you said, check that `response.search_result.items is not None`.

**Comment by YPCrumble** [comment]
The issue isn’t string validation it’s if the api returns zero products for
a search. The incorrect string is just one way to reproduce the issue. For
instance searching for “asdf jkl” probably causes the error as well. So I
think checking against None is a solution.

Thanks for looking into it and merging the other PR’s!
