### ISSUE TITLE
ResponseError using Search_Products

### ISSUE THREAD

**Issue by cairothompson** [sergioteula/python-amazon-paapi#22]
Context
I am attempting to use search_products() to find all items for a given keyword. So I am inputting one keyword and returning the metadata of the items returned in the search. 

However, I am running into a No Response error [AmazonException: ResponseError: NoResults: No results found for your request.]The problem occurs when the input keyword’s  total_results_count is less than then item_count. 

For example, the keyword, ‘norwegian operation’. 

My script is calling search_products like this → products=amazon.search_products(item_count=100, keywords='norwegian operation', search_index = "KindleStore")

And getting the response → [ AmazonException: ResponseError: NoResults: No results found for your request.]  From line 292. 

Environment
 I am using a macOS Catalina  Version 10.15.3 and Python 3.7. 

Steps to Reproduce Errors
products=amazon.search_products(item_count=100, keywords='norwegian operation', search_index = "KindleStore")

Expected Behavior
This issue arises because the keyword ‘norwegian operation’ only has 40 total_result_count. If you change the item_count to 40 or less it does not raise this error.  I would like to get the resulting items regardless of the total results. The paaapi.py allows for a response if there is no results, but not if the total_result_count is less than the item_count.

**Comment by YPCrumble** [comment]
Having the same issue - did you find a solution?

**Comment by YPCrumble** [comment]
@sergioteula @cairothompson I've (partly) found the issue. In the [example provided by Amazon](https://webservices.amazon.com/paapi5/documentation/quick-start/using-sdk.html#python) the search request is formatted like this, and it works:

```
        search_items_request = SearchItemsRequest(
            partner_tag=partner_tag,
            partner_type=PartnerType.ASSOCIATES,
            keywords=keywords,
            search_index=search_index,
            item_count=item_count,
            resources=search_items_resource,
        )
```

Our wrapper is actually passing `items_per_page` to the `item_count` parameter - which seems to be causing the issue. In fact, I've been able to make this library work by deleting the `items_per_page` and `item_page` params, and just setting `item_count` as done in the example above.

However, I haven't found a way to make this library work _with_ pagination.

Hoping this helps shed some light on the issue!
