### ISSUE TITLE
getBrowseNodes function 

### ISSUE THREAD

**Issue by anyarcherty** [sergioteula/python-amazon-paapi#23]
Hey, 

Thanks for creating this great module. We know you may still create the new features. But would you mind to share any plan or schedule to build getBrowseNodes function in this module in future? Since we need this function for our project.

Thanks again!

**Comment by sergioteula** [comment]
Hello, thanks for your comment. There's a new pull request #27 that adds browse node functionality. I'll be glad if you could test it and let me know if there's any issue before merging to master and pushing an update. Thanks!
