### ISSUE TITLE
Remove while loop from search_products

### ISSUE THREAD

**Issue by YPCrumble** [sergioteula/python-amazon-paapi#26]
I think that the `while` loop in search_products is causing more issues than it solves. If someone needs to use the pagination they can use the `item_count` and `items_per_page` parameters built into the SDK.

As currently implemented the `while` loop means that any time a user searches for a product and the search returns fewer than `item_count` results they're actually making two calls to the API, not one call.

So, if the user searches for a very specific title, and the API returns one result, but we have `item_count` set by default to ten items, the wrapper makes a second (unnecessary) call to Amazon.

**Comment by sergioteula** [comment]
This is solved on #27 on line 289:
```
if len(response.search_result.items) < items_per_page:
     break
```
