### ISSUE TITLE
Spell Mistake lenght

### ISSUE THREAD

**Issue by sanind** [sergioteula/python-amazon-paapi#31]
dir(a.product.dimensions)                                                          duce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subcl
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', 
'__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'height', 'lenght', 'width']

>>> a.product.dimensions.length
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Class' object has no attribute 'length'

>>> a.product.dimensions.lenght
<amazon.parse.Class object at 0x03319C70>

**Comment by sergioteula** [comment]
Already fixed and it will be included on next release. Thanks!
