### ISSUE TITLE
TooManyRequests Error

### ISSUE THREAD

**Issue by PeterStavrou** [sergioteula/python-amazon-paapi#32]
I'm getting the below error:

`HTTP response body: {"__type":"com.amazon.paapi5#TooManyRequestsException","Errors":[{"Code":"TooManyRequests","Message":"The request was denied due to request throttling. Please verify the number of requests made per second to the Amazon Product Advertising API."}]}`

I have tried the demo code and have played around with the throttling but still no luck... Any ideas? 

```
from amazon.paapi import AmazonAPI
amazon = AmazonAPI("x", "x", "x", "US", throttling=0.5)
product = amazon.get_product('B01N5IB20Q')
print(product.title)
```

**Comment by PeterStavrou** [comment]
Seems to be fixed now.

**Comment by migcm** [comment]
Same problem with "ES".

**Comment by moveax3** [comment]
Confirm, has TooManyRequests problem even if make a single request with "ES".

**Comment by sergioteula** [comment]
Are you getting the same error when using the [scratchpad](https://webservices.amazon.com/paapi5/scratchpad/index.html)? On the other hand, you can check API rates on [this page](https://webservices.amazon.com/paapi5/documentation/troubleshooting/api-rates.html), maybe your account has reached the usage limit and that's why you're getting the TooManyRequest error.

**Comment by yaph** [comment]
I get the `TooManyRequests` error when I make a request to "DE" using an associate tag created for Germany both using this library and the scratchpad.

When I make a request to "US" with an US associate tag it works with the library and the scratchpad. This seems to be a problem on Amazon's side. There are several issues reported in the AWS forum https://forums.aws.amazon.com/.

**Comment by sergioteula** [comment]
> I get the `TooManyRequests` error when I make a request to "DE" using an associate tag created for Germany both using this library and the scratchpad.
> 
> When I make a request to "US" with an US associate tag it works with the library and the scratchpad.
> 
> There are several related issues reported in the AWS forum https://forums.aws.amazon.com/ where commenters have mentioned request limits as a possible reason. I have no sales for DE during the past 30 days, but I do for US. So I apparently have a request limit of 0 for Germany, which explains the error.

Thanks for your comment, this is the first thing to check when getting the  `TooManyRequests` error. If anyone else is getting this error due to a module malfunction, I will try to solve it.

**Comment by amannguptaggg** [comment]
Same issue , there is no solution on the internet for this problem I error . Because I am searching solution from last 1 year. Din't got anywhere any solution. If anyone have solution. Help will be appreciated.

**Comment by migcm** [comment]
I continue with the same problem, the PA API should be enabled because I have met all the conditions, however, I keep getting the "TooManyRequests" error.

**Comment by Olaf011** [comment]
same

**Comment by sergioteula** [comment]
Since this error is related with Amazon and there's nothing we can do to solve it, I'm moving this to the discussions section and closing this issue. Please go here if you want to say something: https://github.com/sergioteula/python-amazon-paapi/discussions/59
