### ISSUE TITLE
Getting Reviews (feature request)

### ISSUE THREAD

**Issue by PeterStavrou** [sergioteula/python-amazon-paapi#33]
This wrapper is awesome!
Please add the ability to get the star rating of a product (4/5 for example) and customer reviews at the bottom of product pages.

**Comment by sergioteula** [comment]
I would love adding this feature, but it's not possible since the API doesn't provide this information. So the only way to get it is with web scraping. Sorry and thanks for your comment!

**Comment by heisen273** [comment]
@sergioteula amazon API does provide information about product score and number reviews: 
https://webservices.amazon.com/paapi5/documentation/offers.html#merchantinfo

**Comment by ddsky** [comment]
> @sergioteula amazon API does provide information about product score and number reviews: https://webservices.amazon.com/paapi5/documentation/offers.html#merchantinfo

That's reviews for the merchant, not the product
