### ISSUE TITLE
Get Browsenodes Error

### ISSUE THREAD

**Issue by rockou33** [sergioteula/python-amazon-paapi#34]
amazon.get_browsenodes(browse_nodes=['3375301']) gives an error after adding import pprint, six to the parse.py file:

NameError                                 Traceback (most recent call last)
<ipython-input-4-b660ac7bd447> in <module>
      1 bnData = amazon.get_browsenodes(browse_nodes=['3375301'])
      2 
----> 3 print(bnData)

~/opt/miniconda3/lib/python3.7/site-packages/amazon/parse.py in __repr__(self)
     59 
     60     def __repr__(self):
---> 61         return self.to_str()
     62 
     63     def __eq__(self, other):

~/opt/miniconda3/lib/python3.7/site-packages/amazon/parse.py in to_str(self)
     56 
     57     def to_str(self):
---> 58         return pprint.pformat(self.to_dict())
     59 
     60     def __repr__(self):

~/opt/miniconda3/lib/python3.7/site-packages/amazon/parse.py in to_dict(self)
     49             else:
     50                 result[attr] = value
---> 51         if issubclass(BrowseNode, dict):
     52             for key, value in self.items():
     53                 result[key] = value

NameError: name 'BrowseNode' is not defined

Please let me know how to correct. Thanks for this great module.

**Comment by sergioteula** [comment]
I'm not sure if you have defined BrowseNode previously, but it seems to be an issue with your code, not with this module. Could you please confirm this?
