### ISSUE TITLE
Invalid Signature?

### ISSUE THREAD

**Issue by maxiedaniels** [sergioteula/python-amazon-paapi#40]
amazon.exception.AmazonException: ApiException: (401)
Reason: Unauthorized

HTTP response body: {"__type":"com.amazon.paapi5#InvalidSignatureException","Errors":[{"Code":"InvalidSignature","Message":"The request has not been correctly signed. If you are using an AWS SDK, requests are signed for you automatically; otherwise, go to https://webservices.amazon.com/paapi5/documentation/sending-request.html#signing."}]}

Any idea why this is happening?

**Comment by nightmare-rg** [comment]
i also get this error

**Comment by Princic-1837592** [comment]
me too. how can we solve?

**Comment by nightmare-rg** [comment]
I deleted my old keys and regenerate new one. After that it works.

**Comment by sergioteula** [comment]
> I deleted my old keys and regenerate new one. After that it works.

Thanks for the solution, probably the old keys were deprecated.
