### ISSUE TITLE
InvalidSignature Exception when making requests from Google App Engine

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [sergioteula/python-amazon-paapi#44]
I'm trying to do a request which is working just fine from my local console. But once I try to make the same request from App Engine, I get this error:

`ApiException: (401) Reason: Unauthorized HTTP response headers: HTTPHeaderDict({'x-amzn-RequestId': '9c9d9a24-c503-47e7-a912-ca0c79640ec2', 'Content-Length': '321', 'Vary': 'Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent', 'Server': 'Server', 'x-amz-rid': 'M2SS3YJWJG78096WQ7R5', 'Connection': 'keep-alive', 'Date': 'Mon, 19 Oct 2020 22:59:44 GMT', 'Content-Type': 'application/json'}) HTTP response body: {"__type":"com.amazon.paapi5#InvalidSignatureException","Errors":[{"Code":"InvalidSignature","Message":"The request has not been correctly signed. If you are using an AWS SDK, requests are signed for you automatically; otherwise, go to https://webservices.amazon.com/paapi5/documentation/sending-request.html#signing."}]} `

**Comment by sergioteula** [comment]
Have you been able to solve it? If so, it would be nice if you could share it in order to help others with this issue in the future.

**Comment by Karlheinzniebuhr** [comment]
Haven't been able to solve it

**Comment by sergioteula** [comment]
That's so strange, I'm not sure why is happening. If you still need to solve it, you can try generating new credentials.
