### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by barbax7** [sergioteula/python-amazon-paapi#48]
I need to send requests to `webservices.amazon.it` through a proxy server. How can I set it?

**Comment by sergioteula** [comment]
Why do you need to use a proxy for this? The module does not support it now and there's no plan to add it in the near future.

**Comment by barbax7** [comment]
Thanks for your reply.
Actually, I don't need it anymore. The host I was using fo my webapp didn't allow me to send requestes to  `webservices.amazon.it`, but I don't remember the reason why.
I think we can close the issue.
