### ISSUE TITLE
Question: Is it possible to search for products

### ISSUE THREAD

**Issue by b0lle** [sergioteula/python-amazon-paapi#5]
Hey,

is it possible to search for a (or some) products by keywords (e.g. apple iPhone)?

Nice project! Kind regards

**Comment by sergioteula** [comment]
Not yet, but it will be possible in future updates. Thanks for the comment!

**Comment by sergioteula** [comment]
The new update with search functionality is out now, you can upgrade with `pip install python-amazon-paapi --upgrade`. Best regards!
