### ISSUE TITLE
"class Class" is confusing when debugging

### ISSUE THREAD

**Issue by YPCrumble** [sergioteula/python-amazon-paapi#50]
In `amazon/parse.py`, the class named "Class" is confusing - my suggestion would be to create specifically named class instances for each entity. Something like the following:

```
class AmazonBase:
    pass

class AmazonProduct(AmazonBase):
    pass

class AmazonProductInfo(AmazonBase):
    pass

class AmazonContributor(AmazonBase):
    pass

etc.
```

Then, when instantiating (for instance) product.info, we would instantiate `product.info = AmazonProductInfo()`. A contributor would be `contributor = AmazonContributor()`.

When debugging, rather than seeing an error like `TypeError: Object of type Class is not JSON serializable`, which is confusing and doesn't let the user know that the error is part of the Amazon Product API logic, it would be more specific, for instance `TypeError: Object of type AmazonContributor is not JSON serializable`.

Let me know your thoughts @sergioteula ? Happy to write a PR if it's helpful.

**Comment by sergioteula** [comment]
Thanks a lot for your proposal, it will be quite better than it's now. If you don't mind doing a PR, I will check it and merge to master.

**Comment by sergioteula** [comment]
The new version solves this issue, but breaks compatibility with previous ones, so keep in mind you will need to adapt your code.
