### ISSUE TITLE
URL for Amazon Warehouse

### ISSUE THREAD

**Issue by IcArtur** [sergioteula/python-amazon-paapi#51]
Hi, i'm really appreciating your work! I have one thing to ask. I can use Amazon Warehouse link to get the product and this is really cool. I found the way to get the lowest price in the warehouse and that's fantastic. The only thing i can't find is the URL with tag for the Amazon Warehouse's page of the product. 
There is 1 URL and goes always on the page of the standard Amazon.
I hope you can understand what i'm saying and help me 🤣 
Thank you again

**Comment by mikegrep** [comment]
Hello how to get lowest price in thw warehouse?You can give me the method

**Comment by sergioteula** [comment]
> Hi, i'm really appreciating your work! I have one thing to ask. I can use Amazon Warehouse link to get the product and this is really cool. I found the way to get the lowest price in the warehouse and that's fantastic. The only thing i can't find is the URL with tag for the Amazon Warehouse's page of the product.
> There is 1 URL and goes always on the page of the standard Amazon.
> I hope you can understand what i'm saying and help me 🤣
> Thank you again

The API does not provide Warehouse affiliate links, so you should create it yourself by adding `tag=yourtag-21` to the URL.
