### ISSUE TITLE
ModuleNotFoundError: No module named 'amazon'

### ISSUE THREAD

**Issue by Mariano2002** [sergioteula/python-amazon-paapi#52]
That's my simple code:

```
KEY = ""
SECRET = ""
TAG = ""
COUNTRY = "UK"
from amazon.paapi import AmazonAPI
amazon = AmazonAPI(KEY, SECRET, TAG, COUNTRY)
product = amazon.get_product('B01N5IB20Q')
print(product.title)
```
but I get this error
    from amazon.paapi import AmazonAPI
ModuleNotFoundError: No module named 'amazon'

Please can someone help me?

**Comment by barbax7** [comment]
Check if there are other files or directory named `amazon`. Maybe this file you are running.

**Comment by sergioteula** [comment]
Maybe you are using another Python version different from the one you've installed the module on. Please ensure that it is correctly installed and try again, it should work.

**Comment by jensfr1** [comment]
Same problem. Using 4.3.2 it works. With latest version 5.0.1 I get that error. using a windows machine.

**Comment by sergioteula** [comment]
With the last version of this module, you should import is as `from amazon_paapi import AmazonApi`.
