### ISSUE TITLE
InvalidParameterValue

### ISSUE THREAD

**Issue by barbax7** [sergioteula/python-amazon-paapi#54]
Hello there

Whit this link (and others also):
https://www.amazon.it/gp/aw/d/B08QJPMM2J?pf_rd_m=A11IL2PNWYJU7H&storeType=ebooks&pf_rd_p=889e88dc-a023-41fa-8871-b0fc0a00d2b4&pf_rd_r=V50DCEG5YY1HAE7AG1JC&pf_rd_s=mobile-hybrid-3&pf_rd_t=30901&ref_=dbs_f_r_shv_ts_889e88dc-a023-41fa-8871-b0fc0a00d2b4_16&pf_rd_i=1728160031

it returns:

```
InvalidParameterValue","Message":"The value null provided in the request for ItemId is invalid."}]}
```

in `get_product` function.

**Comment by b0lle** [comment]
Hi,
You are not allowed to pass the product link in the get_product function.
Please see the simple example and provide the asin:


from amazon.paapi import AmazonAPI

amazon = AmazonAPI(KEY, SECRET, TAG, COUNTRY)

product = amazon.get_product('B01N5IB20Q')

print(product.title)

**Comment by b0lle** [comment]
In get_product then use the function “get_asin” which tries to infer the asin like this

    # Extract ASIN from URL searching for alphanumeric and 10 digits
    have_asin = re.search(r'(dp|gp/product)/([a-zA-Z0-9]{10})', url)
    return have_asin.group(2) if have_asin else None

In your case the Link does not match the regex, so null is returned and that explains your exception.

**Comment by barbax7** [comment]
But this link is provided directly by Amazon. So how can i solve?

**Comment by sergioteula** [comment]
Thanks for your help, I've already merged your pull request. This change will be available in future updates via pip.

**Comment by barbax7** [comment]
Nice to help you
