### ISSUE TITLE
No module named 'paapi5_python_sdk.get_items_request'

### ISSUE THREAD

**Issue by azeem6755** [sergioteula/python-amazon-paapi#63]
This error occurs on importing the AmazonAPI package. I installed the amightygirl package as well, still getting the same error.
![Screenshot from 2021-04-01 11-09-51](https://user-images.githubusercontent.com/37949109/113248568-d8a2b600-92da-11eb-84bc-9d4e7efea5bd.png)

**Comment by SoothingMist** [comment]
I've a lot more testing to do still but try following Tuval Rotem's advice at https://stackoverflow.com/questions/59488297/how-to-use-amazon-product-advertising-api-5-with-python. Early indications in my own work is that his response gives good results when using Amazon's sample python snippets. (Amazon really should give the source for dependencies.)
