### ISSUE TITLE
Too many request

### ISSUE THREAD

**Issue by tonifergue** [sergioteula/python-amazon-paapi#64]
Hi, I am using your code, and it is fantastic. 

But I am getting the error "Too many requests", I am calling the api with a time.sleep(2) to wait one or two seconds before call again the api. I don't know if it is relative to the api or other problem.

I am not using the api credentials y other programs.

Thanks

**Comment by sergioteula** [comment]
Hello, this is an API related issue, it has nothing to do with this wrapper. You can check this discussion for more information: https://github.com/sergioteula/python-amazon-paapi/discussions/59
