### ISSUE TITLE
Raise Exceptions

### ISSUE THREAD

**Issue by Ak4zh** [sergioteula/python-amazon-paapi#7]
Your library handle all exceptions internally making it impossible for end user to know if a key is revoked, or he is calling api too fast or what's going wrong.

Raise the actual exception and let end users handle it.

For this reason alone I had to migrated to https://github.com/alefiori82/amazon-paapi5 which handles exceptions in a better way.

**Comment by sergioteula** [comment]
Thanks for the advise, this has been already solved and the update is available.
