### ISSUE TITLE
Add optional 'searchindex' parameter to Search product

### ISSUE THREAD

**Issue by YvesWassersleben** [sergioteula/python-amazon-paapi#71]
To refine search results it would be helpful to add the option to include the searchindex parameter to amazon.search_products.
List of locales can be found [here](https://webservices.amazon.com/paapi5/documentation/locale-reference.html#topics) 
e.g. the searchindex list for the us would be [this](https://webservices.amazon.com/paapi5/documentation/locale-reference/united-states.html#search-index)

**Comment by sergioteula** [comment]
Thanks for the suggestion, I will work on this for a future update.

**Comment by sergioteula** [comment]
Hello again, the new update is now available with all available parameters for every method on the official API, including search_index. https://github.com/sergioteula/python-amazon-paapi/blob/f4c694f7eb35d3b75b404633fde32f0028d19b50/amazon_paapi/api.py#L123

By the way, keep in mind that the new version breaks compatibility with previous versions, so you will need to adapt your code.
