### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by Sputkin** [sergioteula/python-amazon-paapi#72]
We want to implement specific operations for each different exception, but currently cannot do that e.g

`amazon.exception.AmazonException: ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Server': 'Server', 'Date': 'Thu, 01 Jul 2021 09:29:50 GMT', 'Content-Type': 'application/json', 'Content-Length': '320', 'Connection': 'keep-alive', 'x-amz-rid': '6M7ZZBARR7KPJ8YEV5JS', 'x-amzn-RequestId': 'd920d9d8-955c-4901-8ec5-e9402df5493e', 'Vary': 'Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent', 'Permissions-Policy': 'interest-cohort=()'})
HTTP response body: {"__type":"com.amazon.paapi5#InvalidSignatureException","Errors":[{"Code":"InvalidSignature","Message":"The request has not been correctly signed. If you are using an AWS SDK, requests are signed for you automatically; otherwise, go to https://webservices.amazon.it/paapi5/documentation/sending-request.html#signing."}]}`

how  handle the **InvalidSignatureException**?

**Comment by sergioteula** [comment]
I'm working on this for the next major update.

**Comment by sergioteula** [comment]
Hello again, the new update is now available with custom exceptions. If you find other suggestions, feel free to open a new issue and I will keep improving it. https://github.com/sergioteula/python-amazon-paapi/blob/master/amazon_paapi/errors/exceptions.py

By the way, keep in mind that the new version breaks compatibility with previous versions, so you will need to adapt your code.
