### ISSUE TITLE
get_products returns multiple products unordered

### ISSUE THREAD

**Issue by sergioteula** [sergioteula/python-amazon-paapi#73]
### Discussed in https://github.com/sergioteula/python-amazon-paapi/discussions/68

<div type='discussions-op-text'>

<sup>Originally posted by **aashishsaini75** June  9, 2021</sup>
@sergioteula I think something is not good with the get_products function, I am passing a list of asins in function to get the price value and also getting the response but the response is not returned in a order of list i am passing like the product[0].prices.price.value response should be the result of first asin of a list but it returned the value randomly of any of the asins.
See the attached images to get better understanding
![image](https://user-images.githubusercontent.com/12483054/121492812-d48ac700-c9f4-11eb-8428-618543280170.jpg)

</div>

**Comment by Sputkin** [comment]
How many calls does this function consume, every 10 products 1 API call right?

**Comment by sergioteula** [comment]
> How many calls does this function consume, every 10 products 1 API call right?

Yes, Amazon only allows getting 10 items per request, so this wrapper makes one request every 10 items.

**Comment by rahulashok360** [comment]
**Is there any way to auto post products we specify to any social media?**

**Comment by sergioteula** [comment]
> **Is there any way to auto post products we specify to any social media?**
> 
> For example: say we mention few book authors in there and it will autopost in social media when the said author/s publish a book.

Hello, this module does not have that functionality, sorry.
