### ISSUE TITLE
ASIN of a product that caused AsinNotFoundException

### ISSUE THREAD

**Issue by jdbit** [sergioteula/python-amazon-paapi#75]
Hi, I'm trying to get a few items in a single request and got an AsinNotFoundException error. How do I know which one ASIN from the list caused the error?
````
items = amazon.get_items(['XXXX', 'YYYYY'])
````
Thanks!

**Comment by sergioteula** [comment]
Hello, it was not possible, but I have just released version 4.1.1 to solve this by including the search string in the exception message.

`Asin not found: the_string_not_containing_the_ASIN`

https://github.com/sergioteula/python-amazon-paapi/releases/tag/v4.1.1
