### ISSUE TITLE
Python script execution may not finish

### ISSUE THREAD

**Issue by kazumasa-kusaba** [sergioteula/python-amazon-paapi#76]
Thank you for useful wrapper module!  
I was just looking for such software.  
It's very helpful!

**But I found a symptomatology that the script execution cannot be finished...**  

I ran the following code for my test on both Mac and Windows.  
main.py:  
```python
# -*- coding: utf-8 -*-
from amazon_paapi import AmazonApi
 
KEY     = "XXXX"
SECRET  = "XXXX"
TAG     = "XXXX"
COUNTRY = "JP"

if __name__ == "__main__":
    amazon = AmazonApi(KEY, SECRET, TAG, COUNTRY)
    items = amazon.get_items(['B01N5IB20Q', 'B01F9G43WU'])
    for item in items:
        print(item.images.primary.large.url) # Primary image url
        print(item.offers.listings[0].price.amount) # Current price
```
<br>

On mac, the execution immediately after launching the terminal didn't finish successfully.  
(It didn't finish until I used Control-C)    
(The second and subsequent executions finished successfully)  
Terminal on Mac:  
```console
testuser@Mac test % python main.py
https://m.media-amazon.com/images/I/41cKE7Id6AL._SL500_.jpg
4490.0
https://m.media-amazon.com/images/I/41s20oziIJL._SL500_.jpg
4424.0
(sometimes freezes here )
```
<br>

On the other hand, the execution on Windows always couldn't finish successfully.  
It always didn't finish until I used Control-C.  
<br>

My environment:  
* Python: `3.8.8` on both OS
* python-amazon-paapi: `4.1.1`
* macOS: `Catelina 10.15.7`
* Windows OS: `Windows 7`

Do you know the cause and workaround?

**Comment by sergioteula** [comment]
I'm not sure what could be happening, your script is so simple. By the way, you can try adding `try/except` block wrapping the `get_items` call to catch any possible exception and avoid crashing the script (in fact, you should always do it like this). Please let us know if you find the solution.

**Comment by sergioteula** [comment]
Have you been able to solve this issue?

**Comment by fredzannarbor** [comment]
I am also encountering this issue using the same code.  OS X, Python 3.8.5, inside virtualenv.  I added 

sleep(5)
print("ahahaha!")

at the end and it executed *once* then no more activity.

**Comment by fredzannarbor** [comment]
It's certainly acting as if something has forgotten to close a connection.

I tried adding "exit()" and "quit" at the end of my script, but that did not work, presumably because the paapi process still has control.

**Comment by netoneplus** [comment]
me too.
I am also in this situation and am in great trouble. I did a lot of research, but in the end I didn't know the cause.
In addition, I think that it is a freeze peculiar to this module that occurs regardless of the command prompt problem in windows 10 in the article.
https://stackoverflow.com/questions/33883530/why-is-my-command-prompt-freezing-on-windows-10/55284493#55284493

**Comment by sergioteula** [comment]
I have created the branch `issue-76-execution-not-finish` to try solving this issue. You can clone it and try if the issue still appears. https://github.com/sergioteula/python-amazon-paapi/tree/issue-76-execution-not-finish

**Comment by sergioteula** [comment]
Any new on this? Have you been able to test this branch?

**Comment by netoneplus** [comment]
I tried it, but it still stops.
Therefore I decided to stop using it.
Thank you so far.

**Comment by sergioteula** [comment]
Sorry to hear that, thanks for the confirmation.

**Comment by ikemo3** [comment]
I had the same problem, but it went away when I ran it with Python 3.9.
