### ISSUE TITLE
The simplifies structure dosent work anymore.

### ISSUE THREAD

**Issue by ltzGabe** [sergioteula/python-amazon-paapi#77]
@sergioteula I know in a recent patch you removed the "structure" file, is it okay if you could please retrieve it or restore it to the site as I am struggling to get data such as offer price without the structure.

**Comment by sergioteula** [comment]
The structure now follows the official documentation for Amazon Product Advertising API, so you can check it for your reference: https://webservices.amazon.com/paapi5/documentation/get-items.html

Moreover, if you're using and IDE like Visual Studio Code, it should help you with suggestions once you type the dot (or pressing CTRL+Space after the dot). If you are not using and IDE, I highly recommend you using VS Code with the Python plugin: https://code.visualstudio.com/
