### ISSUE TITLE
Not an issue but few questions

### ISSUE THREAD

**Issue by Ak4zh** [sergioteula/python-amazon-paapi#8]
Thank you for picking up the pa api5 library develoment.
I have few queries as below:
 
**1. Why are you normalizing links by appending ._AC_.?**
The image url shows highest quality available with if you remove all link functions __xx__ part and keep .jpg simply. This way links are little small and unified with other library.

**2. Can we setup a chat on Telegram, gitter or slack instead so users can us that for non-issue type queries for faster development?**
paapi5 library is much needed right now and a chat will fasten the development, discussion and suggestion.

**Comment by sergioteula** [comment]
First of all, thanks for the suggestion. I have created a group on Telegram where we would be able to discuss better than here. https://t.me/PythonAmazonPAAPI

On the other hand, image links are just as provided by the API itself, I just changed the cropped section to avoid the blank part of the images. So if you want the default image, you can just use the main "large, medium and small" versions or any of the "variants" versions. If you want the version without the blank border, you can use the "cropped" version.

You can check the difference here:
* Default: https://images-na.ssl-images-amazon.com/images/I/71HsZaCJ3hL.jpg
* Cropped: https://images-na.ssl-images-amazon.com/images/I/71HsZaCJ3hL._AC_.jpg

Any other question feel free to ask.

**Comment by Ak4zh** [comment]
Thanks for the discussion group link.
Regarding the images I realised now that non cropped versions are available seperately and cropped version are actually inside cropped attribute so it's nice.
