### ISSUE TITLE
ASIN isnt always returned or accepted

### ISSUE THREAD

**Issue by moshfrid** [sergioteula/python-amazon-paapi#81]
ASINs which exist sometimes return the product without an asin value in the response object, and are sometimes only accepted when they are all uppercase. maybe the asin can be converted to uppercase and inserted into the object asin if it doesnt exist in the response?

**Comment by sergioteula** [comment]
I'm not sure what the issue actually is. You mean that lowercase ASINs are not found or that sometimes the product is correctly retrieved but the ASIN code is not available in the reponse? Posting some examples or code could also help solving the issue. Thanks!

**Comment by moshfrid** [comment]
Well actually both. Lowercase ASINs are sometimes not found at all, and sometimes the product is correctly retrieved but the ASIN code is not available in the response. I have implemented a pre-processing step where I extract all the ASINs and convert them to uppercase before sending the request through and that solves the first issue .

**Comment by sergioteula** [comment]
For the uppercase issue, I think is better converting to uppercase manually like you are doing to prevent issues.

Regarding the issue with the response not including the ASIN code, please send some examples in order to test and solve it. Thanks!

**Comment by moshfrid** [comment]
Well, amazon's asins are not case sensitive, so uppercase and lowercase should be equivalent, so wouldnt it be more efficient to implement a conversion in the asin extraction method? Also, I will try to find at least 1 product with no returned asin in the response

**Comment by sergioteula** [comment]
That was my first idea, but I have tested the same ASIN uppercase and lowercase and it doesn't work with lowercase. As far as I know, ASIN should be all uppercase, so maybe converting to uppercase would be a good option.

**Comment by moshfrid** [comment]
Sounds like converting to uppercase during the asin extraction would be the best bet

**Comment by sergioteula** [comment]
Done, I have just published a new version that includes this change. Once you find an example for the other error, I will work on it. Thanks!

**Comment by sergioteula** [comment]
Since one of the issues is already solved and getting an example for the other issue could take long time, I'm closing this issue and you can open a new one in the future. Thanks!
